# Generated by Django 3.2.7 on 2021-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='Description',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
