# Generated by Django 3.2.7 on 2021-10-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='user',
            new_name='author',
        ),
    ]
