# Generated by Django 3.2.7 on 2021-10-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_user_auction_listing_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='Description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='Title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
    ]
