# Generated by Django 3.2.7 on 2021-10-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211003_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='Tag',
            field=models.CharField(default='No Category Listed', max_length=50),
        ),
    ]
