# Generated by Django 3.2.7 on 2021-10-09 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ManyToManyField(related_name='watchlist', to='auctions.auction_listing')),
                ('user', models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
